# Colors
FIRST_COLOR = 'black'
SECOND_COLOR = '#d9d9d9'
COLLISION_COLOR = '#dc3545'

BUTTON_COLOR = '#bce8f1'
BUTTON_TEXT_COLOR = FIRST_COLOR
BUTTON_ACTIVE_TEXT_COLOR = 'blue'

# Dimensões da janela
WINDOW_WIDTH = 255
WINDOW_HEIGHT = 550
CANVAS_WIDTH = 250
CANVAS_HEIGHT = 500
